name: Update Thought of the Day

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update_quote.py

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'Deepak Pandey'
          git config --global user.email 'deepakpandey911494@gmail.com'
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/848deepak/848deepak.git
          git add README.md
          git commit -m "Update Thought of the Day" || echo "No changes to commit"
          git push origin main
